# Generated by Django 2.1.2 on 2018-10-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='Sigla')),
                ('tipo', models.CharField(choices=[('TECNICO', 'Técnico'), ('GRADUACAO', 'Graduação'), ('PGRADUACAO', ' Pós-graduação')], max_length=30, verbose_name='Tipo de Curso')),
            ],
        ),
    ]
